/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package travelmanagement;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hasnain bhatti
 */
public class AddPakage extends javax.swing.JFrame {
private DatabaseConnection dbconn;//object of DatabaseConnection class
private PreparedStatement pst;//databse statement to insert record
private Connection conn;// use for database  connection
 private java.sql.Statement statement;// sattement variable to execute sql statement
  private   java.sql.ResultSet resultSet; // to get result from database
    /**
     * Creates new form AddPakage
     */
    public AddPakage() {
        initComponents();
        dbconn =  new DatabaseConnection();
        setConn(dbconn.getConnection());
    }
public void setConn(Connection conn){
    this.conn =conn;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pkgIdTf = new javax.swing.JTextField();
        priceTf = new javax.swing.JTextField();
        destinationTf = new javax.swing.JTextField();
        durationTf = new javax.swing.JTextField();
        convayenceBox = new javax.swing.JComboBox<>();
        hotelBox = new javax.swing.JComboBox<>();
        submitButton = new javax.swing.JButton();
        cancelButon = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pakage Details");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("Pakage Details");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Pakage ID");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Convayence Type");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Price Per Head");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Destination");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Duration (In Days)");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Hotel Facility");

        pkgIdTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pkgIdTfKeyTyped(evt);
            }
        });

        priceTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                priceTfKeyTyped(evt);
            }
        });

        destinationTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                destinationTfKeyTyped(evt);
            }
        });

        durationTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                durationTfKeyTyped(evt);
            }
        });

        convayenceBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Airline", "Train", "Bus", "Car" }));

        hotelBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));

        submitButton.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        cancelButon.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        cancelButon.setText("Cancel");
        cancelButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(priceTf, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(destinationTf, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel8))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(convayenceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pkgIdTf, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(hotelBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(durationTf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(cancelButon, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))))))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pkgIdTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(convayenceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(priceTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(destinationTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(durationTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(hotelBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButon, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pkgIdTfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pkgIdTfKeyTyped
        // TODO add your handling code here:
        // store the typed key in a variable
         char a = evt.getKeyChar();
         // check if there is any aplhabet typed
                if(a>='a'&&a<='z'||a>='A'&&a<='Z'){
                    JOptionPane.showMessageDialog(null, "Please enter only numbers");
                    evt.consume();//delete the aplhabet that typed
                }
                else{
                   
                }
    }//GEN-LAST:event_pkgIdTfKeyTyped

    private void priceTfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceTfKeyTyped
        // TODO add your handling code here:
         char a = evt.getKeyChar();
         // check if there is any aplhabet typed
                if(a>='a'&&a<='z'||a>='A'&&a<='Z'){
                    JOptionPane.showMessageDialog(null, "Please enter only numbers");
                    evt.consume();//delete the aplhabet that typed
                }
                else{
                   
                }
    }//GEN-LAST:event_priceTfKeyTyped
//method to check duplicate pakage id
    private boolean duplicateID(){
      try{

                statement = conn.createStatement();
                resultSet = statement.executeQuery("select Pakage_ID from Pakage");
                while(resultSet.next()){
                    // check if there is same id in database than return true
              if(resultSet.getObject("Pakage_ID").toString().equals(pkgIdTf.getText().toString())){
                  return true;
              }
                    
                }
              statement.close();
            }
            catch(Exception e){
                
            }
      return false;
}
    private void destinationTfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_destinationTfKeyTyped
        // TODO add your handling code here:
        char a = evt.getKeyChar();
         // check if there is any aplhabet typed
                 if(a>='0'&&a<='9'){
                    JOptionPane.showMessageDialog(null, "Please enter only aplhabets");
                    evt.consume();//delete the aplhabet that typed
                }
                else{
                   
                }
    }//GEN-LAST:event_destinationTfKeyTyped

    private void durationTfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_durationTfKeyTyped
        // TODO add your handling code here:
        char a = evt.getKeyChar();
         // check if there is any aplhabet typed
                if(a>='a'&&a<='z'||a>='A'&&a<='Z'){
                    JOptionPane.showMessageDialog(null, "Please enter only numbers");
                    evt.consume();//delete the aplhabet that typed
                }
                else{
                   
                }
    }//GEN-LAST:event_durationTfKeyTyped

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        // check for empty textboxes
        if(pkgIdTf.getText().toString().equals("")||priceTf.getText().toString().equals("")||destinationTf.getText().toString().equals("")||durationTf.getText().toString().equals("")){
            // display a mesage if any textbox is empty
            JOptionPane.showMessageDialog(this, "Please fill each information");
        }
        // if duplicate id than show message
        else if(duplicateID()){
             JOptionPane.showMessageDialog(this, "Enter a unique id ");
        }
        else{
           addData();
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void cancelButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_cancelButonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPakage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPakage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPakage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPakage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPakage().setVisible(true);
            }
        });
    }
    private void addData(){
           try{
    
String insertquery = "INSERT INTO Pakage (Pakage_ID,convayencetype,price,destination,duration,hotelFacility)"
         +"VALUES(?,?,?,?,?,?)"  ; 
pst = conn.prepareStatement(insertquery);

pst.setString(1, pkgIdTf.getText());
pst.setString(2, convayenceBox.getSelectedItem().toString());
pst.setString(3, priceTf.getText());
pst.setString(4, destinationTf.getText());
pst.setString(5, durationTf.getText());

pst.setString(6, hotelBox.getSelectedItem().toString());
pst.executeUpdate();
 JOptionPane.showMessageDialog(null, "Record add successfully");
 // set textfiels empty
 pkgIdTf.setText("");
 priceTf.setText("");
 destinationTf.setText("");
 durationTf.setText("");
 
 pst.close();
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Something went wrong......try again");
                
            } 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButon;
    private javax.swing.JComboBox<String> convayenceBox;
    private javax.swing.JTextField destinationTf;
    private javax.swing.JTextField durationTf;
    private javax.swing.JComboBox<String> hotelBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField pkgIdTf;
    private javax.swing.JTextField priceTf;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
